module.exports = {
  COOKIE_ALL: process.env.COOKIE_ALL,
  EMAIL: process.env.EMAIL,
  AUTHORIZATION_CODE: process.env.AUTHORIZATION_CODE,
  PUSHPLUS_TOKEN: process.env.PUSHPLUS_TOKEN,
  DINGDING_WEBHOOK: process.env.DINGDING_WEBHOOK,
  FEISHU_WEBHOOK: process.env.FEISHU_WEBHOOK,
}
